{% set name = "cabean-python" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter
    - algorecell_types
    - cabean

about:
  home: https://github.com/algorecell/cabean-python
  summary: 'Python interface to CABEAN, A Software Tool for the Control of Asynchronous Boolean Networks'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C
